using System.Data;

namespace Grace_DAL.DAL.Inventory.Report
{
    public class R14041DAL : CommonDAL
    {
        public DataTable GetDailySummaryData(string fromDate, string toDate)
        {
            DataTable sql = new DataTable();
            sql = Query($@"select t_1.T_ENTRY_DATE, T14003.T_PRODUCT_NAME, T14004.T_PACK_NAME, T_SALE_PRICE, T_PURCHASE_PRICE, cast(SUM(T_SALE_QUANTITY) as decimal(12,2)) SALE_QUANTITY, cast (SUM(PUR_PRICE)as decimal(12,2))TOTAL_PUR_PRICE, cast (SUM(T_TOTAL_PRICE)as decimal(12,2))T_TOTAL_SALE, cast (SUM(DISCOUNT)as decimal(12,2))DISCOUNT, cast (SUM(T_TOTAL_PRICE-DISCOUNT)-SUM(PUR_PRICE)as decimal(12,2)) LOSE_PROFIT from ( select T14040.T_SALE_DATE T_ENTRY_DATE, T14040.T_MEMO_NO, T_PRODUCT_CODE, T_PACK_CODE, T_SALE_QUANTITY, T14040.T_DISCOUNT, T_PURCHASE_PRICE, T_SALE_PRICE, (T_PURCHASE_PRICE*T_SALE_QUANTITY) PUR_PRICE, ( (T14040.T_DISCOUNT*T_TOTAL_PRICE)/T14040.T_GRAND_TOTAL) DISCOUNT, T_TOTAL_PRICE from T14041 JOIN T14040 ON T14041.T_MEMO_NO =T14040.T_MEMO_NO where CONVERT(date, T14040.T_SALE_DATE ,104) BETWEEN CONVERT(date, '{fromDate}' ,104) AND CONVERT(date, '{toDate}' ,104) )t_1 JOIN T14003 ON t_1.T_PRODUCT_CODE=T14003.T_PRODUCT_CODE JOIN T14004 ON t_1.T_PACK_CODE=T14004.T_PACK_CODE group by t_1.T_ENTRY_DATE, T14003.T_PRODUCT_NAME, T14004.T_PACK_NAME, T_SALE_PRICE, T_PURCHASE_PRICE");
            return sql;
        }
    }
}

